import Header from "@/components/header";
import "./globals.css";
import { robotoVar } from "@/utils/font";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={robotoVar}>
      <body className="font-roboto">
        <Header />
        <main className="mt-12">
          {children}
        </main>
      </body>
    </html>
  );
}
